kind: pipeline
type: docker
name: linux-prod
trigger:
  branch:
    - chore/pipeline
  event:
    - push
steps:
  - name: build linux
    image: cirrusci/flutter:2.0.6
    commands:
      # Keep track of the time when build was started
      - echo $(date -Iseconds) > BUILD_START_TIME
      # Install dependencies (git should be pre-installed)
      - apt-get update && apt-get install --no-install-recommends -y cmake ninja-build clang pkg-config libgtk-3-dev
      - git submodule update --init --recursive
      # Set up flutter config
      - flutter config --no-analytics
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter config --enable-linux-desktop
      # Build the linux app exec
      - flutter build linux --release
